# syntax=docker/dockerfile:latest

ARG TECHMD_OS_DIST="alpine"
ARG TECHMD_OS_RELEASE="3.14.3"
ARG TECHMD_PANDOC_VERSION=2.18
FROM pandoc/latex:${TECHMD_PANDOC_VERSION}-${TECHMD_OS_DIST} as technical-markdown-minimal


ARG TECHMD_OS_DIST
ARG TECHMD_OS_RELEASE

ARG TIME_ZONE="Europe/Zurich"
ARG LOCALE="en_US"
ARG USER_NAME="techmd"
ARG USER_PASSWORD="$USER_NAME"
ARG USER_UID=1000
ARG USER_GID=1000
ARG ZSH_HISTORY="/home/$USER_NAME/.zsh_history"
ARG PYTHON_ENV="/home/$USER_NAME/python-envs/default"
ARG TECHMD_BUILD_VERSION
ARG TECHMD_COMMIT_SHA

ENV TECHMD_CONTAINER_NAME="Technical-Markdown-[min]"
ENV TECHMD_SETUP_DIR="/container-setup"
ENV TECHMD_BUILD_VERSION="$TECHMD_BUILD_VERSION"
ENV TECHMD_COMMIT_SHA="$TECHMD_COMMIT_SHA"

RUN apk add \
    bash \
    curl \
    tree \
    file \
    grep \
    sed \
    findutils \
    sudo \
    tzdata \
    wget \
    zsh \
    ncurses

# Set the locale.
ENV LANG $LOCALE.UTF-8
ENV LC_ALL $LOCALE.UTF-8
ENV LANGUAGE $LOCALE.UTF-8

# Add common scripts.
COPY tools/docker/setup/common $TECHMD_SETUP_DIR/common

# Configure timezone.
COPY tools/docker/setup/setup-time-zone.sh $TECHMD_SETUP_DIR/
RUN chmod +x $TECHMD_SETUP_DIR/setup-time-zone.sh && \
    $TECHMD_SETUP_DIR/setup-time-zone.sh \
    "--non-interactive" \
    --time-zone "$TIME_ZONE"

# Add the user and delete password.
RUN adduser "$USER_NAME" -s /bin/zsh -D -u "$USER_UID" -g "$USER_GID" -h "/home/$USER_NAME" && \
    mkdir -p /etc/sudoers.d && \
    echo "$USER_NAME ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/$USER_NAME" && \
    chmod 0440 "/etc/sudoers.d/$USER_NAME" && \
    chown -R "$USER_NAME:$USER_NAME" /home "$TECHMD_SETUP_DIR"
USER "$USER_NAME"

# Install Git.
COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-git.sh $TECHMD_SETUP_DIR/
RUN chmod +x $TECHMD_SETUP_DIR/setup-git.sh && \
    $TECHMD_SETUP_DIR/setup-git.sh "$TECHMD_OS_DIST"

# Add Zsh shell and plugins.
COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-zsh.sh $TECHMD_SETUP_DIR/
COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/shell $TECHMD_SETUP_DIR/shell/
RUN chmod +x $TECHMD_SETUP_DIR/setup-zsh.sh && \
    $TECHMD_SETUP_DIR/setup-zsh.sh \
    "$TECHMD_OS_DIST"

# Install python requirements.
ENV PATH="$PYTHON_ENV/bin:$PATH"
COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-python.sh tools/docker/setup/python.requirements $TECHMD_SETUP_DIR/
RUN chmod +x $TECHMD_SETUP_DIR/setup-python.sh && \
    $TECHMD_SETUP_DIR/setup-python.sh "$TECHMD_OS_DIST" "$TECHMD_OS_RELEASE" \
    "$PYTHON_ENV" \
    "$TECHMD_SETUP_DIR/python.requirements"

COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-build-tools.sh $TECHMD_SETUP_DIR/
RUN chmod +x $TECHMD_SETUP_DIR/setup-build-tools.sh && \
    $TECHMD_SETUP_DIR/setup-build-tools.sh "$TECHMD_OS_DIST"

COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-shell-tools.sh $TECHMD_SETUP_DIR/
RUN chmod +x $TECHMD_SETUP_DIR/setup-shell-tools.sh && \
    $TECHMD_SETUP_DIR/setup-shell-tools.sh "$TECHMD_OS_DIST"

COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-runtime.sh $TECHMD_SETUP_DIR/
COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-runtime-githooks.sh $TECHMD_SETUP_DIR/

RUN chmod +x $TECHMD_SETUP_DIR/setup-runtime.sh \
    $TECHMD_SETUP_DIR/setup-runtime-githooks.sh

COPY --chown=$USER_NAME:$USER_NAME tools/docker/setup/setup-clean.sh $TECHMD_SETUP_DIR/
RUN chmod +x $TECHMD_SETUP_DIR/setup-clean.sh && \
    $TECHMD_SETUP_DIR/setup-clean.sh "$TECHMD_OS_DIST"

ENTRYPOINT [ "/container-setup/setup-runtime.sh" ]
WORKDIR "/workspace"
CMD [ "zsh" ]
